-- Add version (optimistic locking) and audit timestamps to portfolios
ALTER TABLE portfolios ADD COLUMN IF NOT EXISTS version INT DEFAULT 0 NOT NULL;
ALTER TABLE portfolios ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE portfolios ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

-- Add version and audit timestamps to tax_lots
ALTER TABLE tax_lots ADD COLUMN IF NOT EXISTS version INT DEFAULT 0 NOT NULL;
ALTER TABLE tax_lots ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE tax_lots ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

-- Add version and audit timestamps to transactions
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS version INT DEFAULT 0 NOT NULL;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

-- Add version and audit timestamps to trade_suggestions
ALTER TABLE trade_suggestions ADD COLUMN IF NOT EXISTS version INT DEFAULT 0 NOT NULL;
ALTER TABLE trade_suggestions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE trade_suggestions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

-- Add version and audit timestamps to quotes
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS version INT DEFAULT 0 NOT NULL;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
