apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-rebalancing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-rebalancing-service
  template:
    metadata:
      labels:
        app: portfolio-rebalancing-service
    spec:
      containers:
        - name: portfolio-rebalancing-service
          image: portfolio-rebalancing-ledger-microservices-portfolio-rebalancing-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8301
          envFrom:
            - configMapRef:
                name: portfolio-rebalancing-ledger-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8301
            initialDelaySeconds: 25
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-rebalancing-service
spec:
  ports:
    - port: 8301
      targetPort: 8301
  selector:
    app: portfolio-rebalancing-service
