server:
  port: 8302

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: db-service
          uri: lb://db-service
          predicates:
            - Path=/api/db-service/**
          filters:
            - StripPrefix=2
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/api/stock-service/**
          filters:
            - StripPrefix=2

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

management:
  endpoints:
    web:
      exposure:
        include: health,info
