package com.github.faizalzafri.stockdbservice.controller;

import com.github.faizalzafri.stockdbservice.model.*;
import com.github.faizalzafri.stockdbservice.model.*;
import com.github.faizalzafri.stockdbservice.repository.PortfolioRepository;
import com.github.faizalzafri.stockdbservice.repository.QuoteRepository;
import com.github.faizalzafri.stockdbservice.repository.TaxLotRepository;
import com.github.faizalzafri.stockdbservice.repository.TradeSuggestionRepository;
import com.github.faizalzafri.stockdbservice.service.TransactionService;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/rest/db")
public class DbServiceController {

    private final TransactionService transactionService;

    private final QuoteRepository quoteRepository;
    private final PortfolioRepository portfolioRepository;
    private final TaxLotRepository taxLotRepository;
    private final TradeSuggestionRepository tradeSuggestionRepository;

    public DbServiceController(QuoteRepository quoteRepository, TransactionService transactionService,
                               PortfolioRepository portfolioRepository, TaxLotRepository taxLotRepository,
                               TradeSuggestionRepository tradeSuggestionRepository) {
        this.quoteRepository = quoteRepository;
        this.transactionService = transactionService;
        this.portfolioRepository = portfolioRepository;
        this.taxLotRepository = taxLotRepository;
        this.tradeSuggestionRepository = tradeSuggestionRepository;
    }

    @GetMapping("/{username}")
    public List<String> getQuotes(@PathVariable("username") String username) {

        return getQuotesByUsername(username);
    }

    private List<String> getQuotesByUsername(String username) {
        return quoteRepository.findByUsername(username)
                .stream()
                .map(Quote::getQuote)
                .collect(Collectors.toList());
    }

    @PostMapping("/add")
    public List<String> addQuotes(@RequestBody Quotes quotes) {

        quotes.getQuotes()
                .stream()
                .forEach(quote -> quoteRepository.save(new Quote(quotes.getUsername(), quote)));

        return getQuotesByUsername(quotes.getUsername());
    }

    @PostMapping("/delete/{username}")
    public List<String> delete(@PathVariable("username") final String username) {

        List<Quote> quotes = quoteRepository.findByUsername(username);
        quoteRepository.deleteAll(quotes);

        return getQuotesByUsername(username);
    }

    @PostMapping("/transaction/add")
    public Transaction postTransaction(@RequestBody Transaction transactionRequest) {
        // Set execution timestamp if not provided
        if (transactionRequest.getTimestamp() == null) {
            transactionRequest.setTimestamp(LocalDateTime.now());
        }
        return transactionService.postTransaction(
                transactionRequest.getPortfolioId(),
                transactionRequest.getSymbol(),
                transactionRequest.getType(),
                transactionRequest.getQuantity(),
                transactionRequest.getPrice(),
                transactionRequest.getTimestamp()
        );
    }

    @GetMapping("/portfolio/all")
    public List<Portfolio> getAllPortfolios() {
        return portfolioRepository.findAll();
    }

    @GetMapping("/portfolio/{id}")
    public Portfolio getPortfolioById(@PathVariable("id") Long id) {
        return portfolioRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Portfolio not found: " + id));
    }

    @PostMapping("/portfolio/create")
    public Portfolio createPortfolio(@RequestBody Portfolio portfolio) {
        return portfolioRepository.save(portfolio);
    }
    // Fetch active tax lots for a portfolio (where remainingQuantity > 0)
    @GetMapping("/portfolio/{id}/lots")
    public List<TaxLot> getActiveTaxLots(@PathVariable("id") Long portfolioId) {
        return taxLotRepository.findByPortfolioIdAndRemainingQuantityGreaterThan(
                portfolioId, BigDecimal.ZERO);
    }
    // Fetch pending trade suggestions to prevent duplicate recommendations
    @GetMapping("/suggestions/pending/{portfolioId}")
    public List<TradeSuggestion> getPendingSuggestions(@PathVariable("portfolioId") Long portfolioId) {
        return tradeSuggestionRepository.findByPortfolioIdAndStatus(
                portfolioId, TradeSuggestion.SuggestionStatus.PENDING);
    }
    // Persist new trade suggestions generated by the engine
    @PostMapping("/suggestions/add-all")
    public List<TradeSuggestion> saveSuggestions(@RequestBody List<TradeSuggestion> suggestions) {
        return tradeSuggestionRepository.saveAll(suggestions);
    }

    // Fetch a single trade suggestion by ID
    @GetMapping("/suggestions/{id}")
    public TradeSuggestion getSuggestionById(@PathVariable("id") Long id) {
        return tradeSuggestionRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Suggestion not found: " + id));
    }
}
