name: Java CI with Maven

on:
  pull_request:
    branches: [ "release", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Eureka Service
      run: mvn -f eureka-service/pom.xml clean verify
      
    - name: Build Gateway Service
      run: mvn -f gateway-service/pom.xml clean verify
      
    - name: Build DB Service
      run: mvn -f stock-db-service/pom.xml clean verify
      
    - name: Build Stock Service
      run: mvn -f stock-service/pom.xml clean verify
